### ISSUE TITLE
16 spotlight_resources

### ISSUE THREAD

**Issue by sephirothkod** [UVicLibrary/CustomSpotlightInstance#10]
!ruby/hash:ActionController::Parameters
to
!ruby/hash:ActiveSupport::HashWithIndifferentAccess

add columns
"upload_id" integer DEFAULT NULL, ??
"file_name" varchar DEFAULT NULL, duplicate from url
"uid" varchar DEFAULT NULL, null
"compound_ids" text DEFAULT NULL, copy from data column:
{spotlight_upload_compound_object_is: \'1\' items:\n- 1-458\n- 1-459}

add extra column, "parent" varchar, DEFAULT NULL, copy from data column: {spotlight_upload_parent_tesim: \"/spotlight/wwi/catalog/1-590/0\"}

**Comment by sephirothkod** [comment]
upload_id should be set to the id column.

**Comment by sephirothkod** [comment]
a new featured image needs to be created for every resource, the upload_id should be the featured image id. featured image needs FeaturedImage[:image] to be set to the url/file_name from the resource.

**Comment by eltiffster** [comment]
From email:

While I was trying to figure out the indexing issue, I realized there were at least 2 fields that were creating problems: “spotlight_upload_dc_Date_tesim” and “spotlight_upload_dc_Date_Created_Searchable_tesim” (which I changed to _tesi and then it indexed correctly).

Both the resource and the sidecar need to be changed for that to work because the reindexing process pulls from the sidecar. Not sure if you wanted to change that in the SQL file.

Interestingly, I think _tesim still works for date fields that don’t have special characters like – or :, but I guess they should all be consistent anyway.

I can’t seem to find the mp3s for the wwi exhibit in the featured_images/images folder and some of the items are probably duplicated. For example, Dodd’s Scrapbook pg 46 (resource_id: 528) is in image folders 402 and 901 but should be in 901 only (there should be an mp3 in 402). I’ll take a look at the featured images dump and see if the answer’s in there somewhere.
